syntax = "proto3";

package google.crypto.tink;

option java_package = "cc.ddrpa.crypto.tink.proto";
option java_multiple_files = true;
option objc_class_prefix = "TINKPB";

message Sm2SignatureKeyFormat {
  uint32 version = 1;
}

// key_type: type.googleapis.com/ddrpa.crypto.tink.Sm2SignaturePublicKey
message Sm2SignaturePublicKey {
  uint32 version = 1;
  bytes x = 2;
  bytes y = 3;
}

// key_type: type.googleapis.com/ddrpa.crypto.tink.Sm2SignaturePrivateKey
message Sm2SignaturePrivateKey {
  uint32 version = 1;
  Sm2SignaturePublicKey public_key = 2;
  bytes key_value = 3;
}
